using System;
using System.Linq;
using Skahal.Infrastructure.Framework.Domain;
using Skahal.Infrastructure.Framework.Repositories;
using System.IO;
using UnityEngine;
using System.Collections.Generic;
using System.Globalization;
using Skahal.Infrastructure.Framework.Logging;
using ProtoBuf.Meta;

namespace Skahal.Infrastructure.Unity.Repositories
{
	/// <summary>
	/// Protobuf repository base.
	/// </summary>
	public abstract class ProtobufRepositoryBase<TEntity> : IRepository<TEntity> where TEntity : class, IAggregateRoot
	{
		#region Fields
		private string m_repositoryFolder;

		/// <summary>
		/// The Protobuf-net pre generate serializer.
		/// <remarks>
		/// This class is generated by the tool Skahal.Core.ProtobufCompiledSerializerGen.
		/// </remarks>
		/// <see>http://www.frictionpointstudios.com/blog/2011/3/31/using-protobuf-net-serialization-in-unity-iphone.html</see>
		/// </summary>
		private ProtobufSerializer m_serializer;
		#endregion

		#region Constructors
		/// <summary>
		/// Initializes a new instance of the <see cref="Skahal.Infrastructure.Unity.Repositories.ProtobufRepositoryBase`1"/> class.
		/// </summary>
		protected ProtobufRepositoryBase()
		{
			var entityType = typeof(TEntity);

			m_repositoryFolder = Path.Combine(Application.persistentDataPath, entityType.FullName);
		
			if(!Directory.Exists(m_repositoryFolder))
			{
				Directory.CreateDirectory(m_repositoryFolder);
			}

			m_serializer = new ProtobufSerializer ();
			LogService.Debug("{0}: using folder '{1}' as data folder.", GetType().Name, m_repositoryFolder);
		}
		#endregion

		#region Methods
		/// <summary>
		/// Find an entity by the filter.
		/// </summary>
		/// <param name="filter">Filter.</param>
		public TEntity Find(Func<TEntity, bool> filter)
		{
			TEntity result = null;
			var allIds = GetAllIds ();
	
			foreach (var id in allIds) 
			{
				using(var stream = File.OpenRead (GetFileName(id)))
				{
					var entity = (TEntity)m_serializer.Deserialize(stream, null, typeof(TEntity));

					if(filter(entity))
					{
						result = entity;
						break;
					}
				}		
			}

			return result;
		}
		
		/// <summary>
		/// Create the specified entity.
		/// </summary>
		/// <param name="entity">Entity.</param>
		public virtual TEntity Create (TEntity entity)
		{
			entity.Id = GetLastId () + 1;
			
			Modify(entity);

			return entity;
		}
		
		/// <summary>
		/// Delete the specified entity.
		/// </summary>
		/// <param name="entity">Entity.</param>
		public virtual void Delete(TEntity entity)
		{
			File.Delete(GetFileName(entity.Id));
		}
		
		/// <summary>
		/// Delete the specified entity.
		/// </summary>
		/// <param name="id">Identifier.</param>
		public virtual void Delete (int id)
		{ 
			File.Delete(GetFileName (id));
		} 
		
		/// <summary>
		/// Modify the specified entity.
		/// </summary>
		/// <param name="entity">Entity.</param>
		public virtual void Modify (TEntity entity)
		{
			using(var stream = File.OpenWrite (GetFileName(entity.Id)))
			{
				m_serializer.Serialize(stream, entity);
			}
		}
		#endregion	
		
		#region Fields
		private string GetFileName (long id)
		{
			return Path.Combine(m_repositoryFolder, id + ".bin");
		}
		
		private long GetLastId ()
		{
			long result = 0;
			var ids = GetAllIds ();

			if (ids.Length > 0) {
				result = ids [ids.Length - 1];
			}

			return result;
		}

		private long[] GetAllIds()
		{
			var files = Directory.GetFiles(m_repositoryFolder, "*.bin");
			LogService.Debug("{0}: {1} files found on data folder '{2}'.", GetType().Name, files.Length, m_repositoryFolder);

			var ids = new long[files.Length];

			for (var i = 0; i < files.Length; i++) {
				ids [i] = long.Parse (Path.GetFileNameWithoutExtension(files[i]));
			}

			return ids;
		}
		#endregion
	}
}

